theme: noesya-hugo-theme
_merge: deep
params:
  debug:
    productionUrl: https://sane.noesya.coop
  ecosystem: sane
  logo:
    header: "/assets/images/logo.svg"
  summary:
    position: hero
  i18n:
    positions: none